name: testing, linting, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:css
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        uses: lost-pixel/lost-pixel@next
        if: always()
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}

